easy_admin:
   site_name: 'ProStages'
   design:
        brand_color: 'red'
        assets:
             favicon: '/ico/stud.ico'
   list:
      max_results: 30


    # ...



   entities:
       # # List the entity class name you want to manage
         - App\Entity\Formation
         - App\Entity\Stage
         - App\Entity\Entreprise
         - App\Entity\User
